---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# mercadoedu.tc

<!-- badges: start -->
<!-- badges: end -->

Repositório para treinar o modelo de classificação de texto dos nomes de curso da mercadoedu, utilizando o algoritmo [TF-IDF](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html) de 1 até 3 n-gramas e o classificador [LinearSVC](https://scikit-learn.org/stable/modules/generated/sklearn.svm.LinearSVC.html) ambos da biblioteca [scikit-learn](https://scikit-learn.org/).

# Table of Contents
- [Preparação do ambiente](#prepação-do-ambiente)
  - [Baixando código](#baixando-código)
  - [Instalação das dependências](#instalação-das-dependências)
  - [Variáveis de ambiente](#variáveis-de-ambiente)
- [Análise com aprendizado de máquina](#análise-com-aprendizado-de-máquina)
  - [Rotina principal](#rotina-principal)
  - [Salvar modelo](#salvar-modelo)
  
# Rotinas

Para clonar o repositório e visualizar as rotinas utilize os comandos abaixo conforme o gif:

```{bash eval=FALSE, echo=TRUE}

git clone https://github.com/fcsestme/mercadoedu.tc.git

```

# Rotina principal

## Depedências
### Atualizando ubuntu e as dependências necessárias
### Instalando bibliotecas necessárias em python e as stopwords
### Definindo variáveis de ambiente
### Definindo credenciais do AWS

## Avaliação dos modelos e treino
### Préprocessamento
### Validação Cruzada
### Avaliação de Modelos
### Treino
### Exportação de Modelos

## Exportação dos Gráficos
### Gráfico da Validação Cruzada
### Gráfico da Matriz de Confusão
### Log

## Limpeza dos arquivos temporários
